### ISSUE TITLE
CookieUtil  Control character in cookie value or attribute.

### ISSUE THREAD

**Issue by venusdrogon** [venusdrogon/feilong-servlet#7]
```JAVA


22:23:53 DEBUG (CookieUtil.java:385) addCookie() - [addCookie],cookieEntity info:[{"path":"/","maxAge":-1,"domain":"","name":"nickName","comment":"","httpOnly":false,"secure":false,"value":"金鑫","version":0}]


22:23:53 DEBUG (AbstractHandlerExceptionResolver.java:132) resolveException() - Resolving exception from handler [public com.nebula.web.controller.NebulaReturnResult com.store.web.controller.member.MemberRegisterController.register(com.nebula.web.controller.member.form.RegisterForm,org.springframework.validation.BindingResult,javax.servlet.http.HttpServletRequest,javax.servlet.http.HttpServletResponse,org.springframework.ui.Model)]: java.lang.IllegalArgumentException: Control character in cookie value or attribute.
22:23:53 DEBUG (SimpleMappingExceptionResolver.java:249) findMatchingViewName() - Resolving to view 'forward:/errors/500' for exception of type [java.lang.IllegalArgumentException], based on exception mapping [java.lang.Throwable]
22:23:53 ERROR (ExceptionResolver.java:60) getModelAndView() - 
java.lang.IllegalArgumentException: Control character in cookie value or attribute.
	at org.apache.tomcat.util.http.CookieSupport.isHttpSeparator(CookieSupport.java:193)
	at org.apache.tomcat.util.http.CookieSupport.isHttpToken(CookieSupport.java:217)
	at org.apache.tomcat.util.http.ServerCookie.appendCookieValue(ServerCookie.java:186)
	at org.apache.catalina.connector.Response.generateCookieString(Response.java:1032)
	at org.apache.catalina.connector.Response.addCookie(Response.java:974)
	at org.apache.catalina.connector.ResponseFacade.addCookie(ResponseFacade.java:381)
	at javax.servlet.http.HttpServletResponseWrapper.addCookie(HttpServletResponseWrapper.java:58)
	at com.feilong.servlet.http.CookieUtil.addCookie(CookieUtil.java:387)
	at com.store.web.controller.member.MemberRegisterController.register(MemberRegisterController.java:220)

```

```JAVA

CookieEntity cookie = new CookieEntity("nickName", memberDetails.getNickName()); 

CookieUtil.addCookie(cookie, response);

```

**Comment by venusdrogon** [comment]
http://blog.csdn.net/liulong547026741/article/details/11553923

**Comment by venusdrogon** [comment]
```JAVA

  @RequestMapping(value = { "/testcookie" })
    public void testCookie(HttpServletRequest request,HttpServletResponse response){
        CookieUtil.addCookie("test", "飞龙", response);
    }


```

**Comment by venusdrogon** [comment]
https://stackoverflow.com/questions/9109318/java-lang-illegalargumentexception-control-character-in-cookie-value-or-attribu

**Comment by venusdrogon** [comment]
如果 调用者 已经加密了 ,再加密 就会有问题

%E9%A3%9E%E9%BE%99

%25E9%25A3%259E%25E9%25BE%2599

**Comment by venusdrogon** [comment]
CookieUtil 只做 cookie 的操作 

如果要加密 , 请使用 CookieAccessor
